# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache = false

# Added this to toggle auto Javadoc & sources because some may not want this to save resources.
autoJavadocSources = true

# Fabric
# https://fabricmc.net/develop
mc_version = 1.18.2
java_version = 17
loader_version = 0.18.4
loom_version = 1.17-SNAPSHOT
fabric_api_version = 0.77.0+1.18.2
yarn_version = 1.18.2+build.4

# Parchment
# https://parchmentmc.org/docs/getting-started
parchment_version = 2022.11.06

# Mod Properties
mod_id = example_mod
mod_name = Example Mod
mod_main_class = ExampleMod
mod_license = All Rights Reserved
mod_version = 1.0
mod_group = com.example.example_mod
mod_authors = Me
mod_credits = My Friend
mod_description = An example mod.
mod_homepage = https://modrinth.com/mod/
mod_sources = https://github.com/Me/Example-Mod
archives_base_name = example_mod-fabric

# Dependencies
porting_lib_version = 1.2.1584-beta+1.18.2
forge_config_api_port_version = 3.2.4
create_version = 0.5.1-f-build.1415+mc1.18.2
hephaestus_version = 1.18.2-3.5.2.312
mantle_version = 1.18.2-1.9.156
star_version = 1.3
ad_astra_version = 1.0.9
cloth_config_version = 6.5.102
teamreborn_energy_version = 2.2.0

modmenu_version = 3.2.5
rei_version = 8.4.778
lazydfu_version = 0.1.2
dcwa_version = 2.0

